### ISSUE TITLE
not working recently, please help

### ISSUE THREAD

**Issue by cr2069** [xMNG/Microsoft-Rewards-Bot#102]
It happened like 3 days ago, my scripts don't work anymore(worked perfectly before that), nothing really changed in my side. Log(part) shows error:

ERROR :: root :: Failure at main()
Traceback (most recent call last):
  File "....\ms_rewards.py", line 889, in <module>
    browser = browser_setup(parser.headless_setting, MOBILE_USER_AGENT)
  File "....\ms_rewards.py", line 257, in browser_setup
    chrome_obj = webdriver.Chrome(path, chrome_options=options)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 6.1.7601 SP1 x86_64)

I updated Python to latest 3.7.4, same problem.

Can anyone help? Thanks.

**Comment by cr2069** [comment]
I updated chromedriver(manually updated or delete it from the folder), still the script doesn't work. It gives different error though:

**Comment by cr2069** [comment]
Seems working now, even it still gives some errors....so I will close this issue. Thanks.
