### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Emeraldop** [xMNG/Microsoft-Rewards-Bot#120]
2019-09-28 15:34:37,548 :: ERROR :: root :: Webdriver Error for click by ID to check object
Traceback (most recent call last):
  File "ms_rewards.py", line 464, in click_by_id
    browser.find_element_by_id(obj_id).click()
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"check"}
  (Session info: headless chrome=77.0.3865.90)
  (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Windows NT 10.0.17763 x86_64)

2019-09-28 15:34:40,620 :: ERROR :: root :: WebDriverException while executing pc portion
Traceback (most recent call last):
  File "ms_rewards.py", line 930, in <module>
    iter_dailies()
  File "ms_rewards.py", line 627, in iter_dailies
    click_quiz()
  File "ms_rewards.py", line 710, in click_quiz
    random.choice(choices).click()
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: headless chrome=77.0.3865.90)
  (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Windows NT 10.0.17763 x86_64)

**Comment by Brenex** [comment]
This can be merged with https://github.com/xMNG/Microsoft-Rewards-Bot/issues/121

**Comment by Brenex** [comment]
this is fixed in the newest version. Has been back to normal and working well for the past few days
