### ISSUE TITLE
Message: element not interactable

### ISSUE THREAD

**Issue by lukedukeus** [xMNG/Microsoft-Rewards-Bot#20]
Im seeing this,what am i doing wrong?
It doesnt do the dailies
'
2019-03-01 20:13:34,212 :: INFO :: root :: -------------------------MOBILE-------------------------
2019-03-01 20:13:36,371 :: INFO :: root :: Logging in ________@outlook.com...
2019-03-01 20:13:50,343 :: INFO :: root :: Search Start
2019-03-01 20:13:57,398 :: INFO :: root :: Stopped at search number 0
2019-03-01 20:13:59,507 :: INFO :: root :: -------------------------PC-------------------------
2019-03-01 20:14:01,716 :: INFO :: root :: Logging in ________@outlook.com...
2019-03-01 20:14:16,450 :: INFO :: root :: Search Start
2019-03-01 20:14:25,005 :: INFO :: root :: Stopped at search number 0
2019-03-01 20:14:32,724 :: INFO :: root :: Number of incomplete offers: 5
2019-03-01 20:14:35,971 :: ERROR :: root :: WebDriverException while executing pc portion
Traceback (most recent call last):
  File "ms_rewards.py", line 857, in <module>
    iter_dailies()
  File "ms_rewards.py", line 548, in iter_dailies
    offer.click()
  File "C:\Users\John\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\John\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\John\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\John\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: headless chrome=72.0.3626.119)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)'

**Comment by lukedukeus** [comment]
nevermind, just read issue #19
