### ISSUE TITLE
Mobile Search Not Working

### ISSUE THREAD

**Issue by pearlheartgtr** [xMNG/Microsoft-Rewards-Bot#23]
2019-03-05 22:16:37,571 :: INFO :: root :: -------------------------PC-------------------------
2019-03-05 22:16:40,597 :: INFO :: root :: Logging in XXXXX...
2019-03-05 22:17:07,945 :: INFO :: root :: Search Start
2019-03-05 22:17:16,169 :: INFO :: root :: Stopped at search number 0
2019-03-05 22:17:30,412 :: INFO :: root :: No dailies found.
2019-03-05 22:17:34,537 :: INFO :: root :: Total points = 3625
2019-03-05 22:17:34,537 :: INFO :: root :: PC points = 150/150
2019-03-05 22:17:34,537 :: INFO :: root :: Edge points = 20/20
2019-03-05 22:17:34,537 :: INFO :: root :: Mobile points = 0/100
2019-03-05 22:17:36,880 :: INFO :: root :: -------------------------MOBILE-------------------------
2019-03-05 22:17:40,207 :: INFO :: root :: Logging in username...
2019-03-05 22:17:56,556 :: ERROR :: root :: uhfLogo element Not Visible - Timeout Exception
2019-03-05 22:17:56,556 :: ERROR :: root :: uhfLogo cannot be located.
Traceback (most recent call last):
  File "ms_rewards.py", line 254, in wait_until_visible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-03-05 22:18:03,369 :: INFO :: root :: Search Start
2019-03-05 22:18:20,598 :: ERROR :: root :: //*[@id="flyoutContent"] element Not Visible - Timeout Exception
2019-03-05 22:18:20,598 :: ERROR :: root :: //*[@id="flyoutContent"] cannot be located.
Traceback (most recent call last):
  File "ms_rewards.py", line 254, in wait_until_visible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-03-05 22:18:21,259 :: INFO :: root :: WebDriverException while executing mobile portion
Traceback (most recent call last):
  File "ms_rewards.py", line 777, in <module>
    search(search_list, mobile_search=True)
  File "ms_rewards.py", line 454, in search
    if get_point_total(mobile=True):
  File "ms_rewards.py", line 660, in get_point_total
    pcsearch = browser.find_element_by_class_name('pcsearch')
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 563, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"pcsearch"}
  (Session info: headless chrome=72.0.3626.119)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

2019-03-05 22:18:23,601 :: INFO :: root :: -------------------------PC-------------------------
2019-03-05 22:18:26,192 :: INFO :: root :: Logging in username...
2019-03-05 22:18:41,647 :: ERROR :: root :: uhfLogo element Not Visible - Timeout Exception
2019-03-05 22:18:41,647 :: ERROR :: root :: uhfLogo cannot be located.
Traceback (most recent call last):
  File "ms_rewards.py", line 254, in wait_until_visible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-03-05 22:18:48,430 :: INFO :: root :: Search Start
2019-03-05 22:19:20,632 :: ERROR :: root :: sb_form_q element Not Visible - Timeout Exception
2019-03-05 22:19:20,632 :: ERROR :: root :: sb_form_q cannot be located.
Traceback (most recent call last):
  File "ms_rewards.py", line 254, in wait_until_visible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-03-05 22:19:21,869 :: ERROR :: root :: Send key by ID to sb_form_q element, no such element
Traceback (most recent call last):
  File "ms_rewards.py", line 370, in clear_by_id
    browser.find_element_by_id(obj_id).clear()
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"sb_form_q"}
  (Session info: headless chrome=72.0.3626.119)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

2019-03-05 22:19:21,870 :: ERROR :: root :: sb_form_q cannot be located.
Traceback (most recent call last):
  File "ms_rewards.py", line 370, in clear_by_id
    browser.find_element_by_id(obj_id).clear()
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"sb_form_q"}
  (Session info: headless chrome=72.0.3626.119)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

2019-03-05 22:19:23,584 :: ERROR :: root :: Send key by ID to sb_form_q element, no such element
Traceback (most recent call last):
  File "ms_rewards.py", line 324, in send_key_by_id
    browser.find_element_by_id(obj_id).send_keys(key)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"sb_form_q"}
  (Session info: headless chrome=72.0.3626.119)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

2019-03-05 22:19:23,585 :: ERROR :: root :: sb_form_q cannot be located.
Traceback (most recent call last):
  File "ms_rewards.py", line 324, in send_key_by_id
    browser.find_element_by_id(obj_id).send_keys(key)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"sb_form_q"}
  (Session info: headless chrome=72.0.3626.119)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

2019-03-05 22:19:25,324 :: ERROR :: root :: Send key by ID to sb_form_q element, no such element
Traceback (most recent call last):
  File "ms_rewards.py", line 324, in send_key_by_id
    browser.find_element_by_id(obj_id).send_keys(key)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"sb_form_q"}
  (Session info: headless chrome=72.0.3626.119)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

2019-03-05 22:19:25,325 :: ERROR :: root :: sb_form_q cannot be located.
Traceback (most recent call last):
  File "ms_rewards.py", line 324, in send_key_by_id
    browser.find_element_by_id(obj_id).send_keys(key)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"sb_form_q"}
  (Session info: headless chrome=72.0.3626.119)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

2019-03-05 22:19:32,170 :: ERROR :: root :: WebDriverException while executing pc portion
Traceback (most recent call last):
  File "ms_rewards.py", line 799, in <module>
    search(search_list)
  File "ms_rewards.py", line 460, in search
    if get_point_total(pc=True):
  File "ms_rewards.py", line 660, in get_point_total
    pcsearch = browser.find_element_by_class_name('pcsearch')
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 563, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"pcsearch"}
  (Session info: headless chrome=72.0.3626.119)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

**Comment by pearlheartgtr** [comment]
Working again. Seems when they changed the layout on the Earn page, it did something. Then they changed it back and it's working again.
