### ISSUE TITLE
Selenium

### ISSUE THREAD

**Issue by Galanthis** [xMNG/Microsoft-Rewards-Bot#25]
Trying to get the program up and running on a raspberry Pi.  running into error
 python3 ./ms_rewards.py
Traceback (most recent call last):
  File "./ms_rewards.py", line 21, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

When I try just Python, 
**Traceback (most recent call last):
  File "./ms_rewards.py", line 737, in <module>
    init_logging()
  File "./ms_rewards.py", line 49, in init_logging
    os.makedirs('logs', exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
**
Not sure what I am doing wrong and new to all of this so any help would greatly be appreciated.

**Comment by ShoGinn** [comment]
@Galanthis You are correct, this uses python3 not python2..

If you reference the README.
```
Enter into cmd/terminal/shell: pip install -r requirements.txt

This installs dependencies (selenium)
```

If you've done that let us know!

**Comment by Galanthis** [comment]
Thanks for the response, Yep. I installed the requirements and still wasn't able to get it to work.

________________________________

**Comment by Galanthis** [comment]
galanthis@galanthis-desktop:~/Downloads/Microsoft-Rewards-Bot-master$ pip install -r requirements.txt
Collecting selenium==3.14.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/b8/53/9cafbb616d20c7624ff31bcabd82e5cc9823206267664e68aa8acdde4629/selenium-3.14.0-py2.py3-none-any.whl
Collecting requests==2.21.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting urllib3 (from selenium==3.14.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.21.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests==2.21.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.21.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: urllib3, selenium, certifi, idna, chardet, requests
Successfully installed certifi-2019.3.9 chardet-3.0.4 idna-2.8 requests-2.21.0 selenium-3.14.0 urllib3-1.24.1
galanthis@galanthis-desktop:~/Downloads/Microsoft-Rewards-Bot-master$ ls
email_links.txt.example  geckodriver.log  ms_rewards_login_dict.json  ms_rewards.py  README.md  requirements.txt  test.py
galanthis@galanthis-desktop:~/Downloads/Microsoft-Rewards-Bot-master$ python3 ms_rewards.py --headless --mobile --pc --quiz
Traceback (most recent call last):
  File "ms_rewards.py", line 21, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
galanthis@galanthis-desktop:~/Downloads/Microsoft-Rewards-Bot-master$


________________________________

**Comment by ShoGinn** [comment]
My guess is that with python3 you are not linked to the correct packages.

try 
```
pip3 install -r requirements.txt
```

**Comment by ShoGinn** [comment]
FYI you can check with:
```
pip list
```
or
```
pip3 list
```
to see if you have selenium installed.

**Comment by Galanthis** [comment]
That was the magic step loading pip3.  going to validate that it works and will get back to you. thanks very much for the information. appreciate it.

**Comment by xMNG** [comment]
Hi @Galanthis, were you able to verify the script working on raspberry pi? Was thinking about migrating to self-hosted. Thanks.

**Comment by jbfreels** [comment]
@xMNG I'm trying to get this script working on Raspberry Pi after failing to get it working in a Docker container.  It appears the chromedriver might be incorrect?  I have the same error on the pi as I do in docker testing with many different base images.  
```
2019-05-07 14:00:14 : INFO :: rewardsbot.logger :: rewardsbot : --------------------------------------------------
2019-05-07 14:00:14 : INFO :: rewardsbot.logger :: rewardsbot : -----------------------New------------------------
2019-05-07 14:00:14 : INFO :: rewardsbot.logger :: rewardsbot : --------------------------------------------------
2019-05-07 14:00:14 : INFO :: rewardsbot.logger :: rewardsbot : Version: 2019.05.04-dev
2019-05-07 14:00:14 : INFO :: <<REDACTED>> :: ms_rewards : Started For user: <<REDACTED>>
Traceback (most recent call last):
  File "msrewards", line 5, in <module>
    main()
  File "/home/jbfreels/src/mrb/rewardsbot/rewardsbot.py", line 59, in main
    rewards.dailyrewards()
  File "/home/jbfreels/src/mrb/rewardsbot/ms_rewards.py", line 680, in dailyrewards
    self.run_it()
  File "/home/jbfreels/src/mrb/rewardsbot/ms_rewards.py", line 687, in run_it
    self.login(self.PC_USER_AGENT)
  File "/home/jbfreels/src/mrb/rewardsbot/ms_rewards.py", line 319, in login
    self.driver_setup(user_agent)
  File "/home/jbfreels/src/mrb/rewardsbot/ms_rewards.py", line 66, in driver_setup
    self.driver = driver_init.get_webdriver(user_agent=user_agent)
  File "/home/jbfreels/src/mrb/rewardsbot/driver.py", line 80, in get_webdriver
    chrome_obj = webdriver.Chrome(path, chrome_options=options)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'drivers/chromedriver'
```
```
  .',;:cc;,'.    .,;::c:,,.    jbfreels@pidock 
 ,ooolcloooo:  'oooooccloo:    --------------- 
 .looooc;;:ol  :oc;;:ooooo'    OS: Raspbian GNU/Linux 9.9 (stretch) armv7l 
   ;oooooo:      ,ooooooc.     Model: Raspberry Pi 3 Model B Rev 1.2 
     .,:;'.       .;:;'.       Kernel: 4.14.98-v7+ 
     .... ..'''''. ....        Uptime: 1 hour, 37 minutes 
   .''.   ..'''''.  ..''.      Packages: 545 
   ..  .....    .....  ..      Shell: bash 4.4.12 
  .  .'''''''  .''''''.  .     CPU: ARMv7 rev 4 (v7l) (4) @ 1.2GHz 
.'' .''''''''  .'''''''. ''.   Memory: 94MB / 927MB 
'''  '''''''    .''''''  '''    
.'    ........... ...    .'.   ████████████████████████ 
  ....    ''''''''.   .''.      
  '''''.  ''''''''. .''''' 
   '''''.  .'''''. .'''''. 
    ..''.     .    .''.. 
          .''''''' 
           ...... 

jbfreels@pidock:~/src/mrb $ python3.6 --version
Python 3.6.8
jbfreels@pidock:~/src/mrb $ pip3.6 list
Package    Version 
---------- --------
certifi    2019.3.9
chardet    3.0.4   
idna       2.8     
pip        18.1    
requests   2.21.0  
selenium   3.14.0  
setuptools 40.6.2  
tabulate   0.8.3   
urllib3    1.25.2  

```
Let me know if there is any further information needed.  Same error with mainline and on dev branch.

**Comment by jbfreels** [comment]
Appears it was an issue with the `chromedriver`.  I installed the `chromium-chromedriver` package and then `cp /usr/bin/chromedriver ./drivers` and now all appears good.

**Comment by ShoGinn** [comment]
@jbfreels looks to be an issue with armhf processor of the pi.

Let me take a look and see if we can make this more multi-arch friendly ;)

**Comment by ShoGinn** [comment]
I made some changes to the dev version to support the raspberry pi.

see dd1891a

**Comment by Ren00d** [comment]
Can someone give a hand with raspberry Pi setup .. I'm pretty new to coding would appreciate some help ...
I was able to clone the files to the pi then modify account names and passwords...
I was able to install requirements with the pip3 install requirements.txt
Then what ?
I open a CMD window and type python msrewards --headless -- mobile --pc --quiz
.... I tried and it tells me:
Importerror: cannot import name VERSION

**Comment by ShoGinn** [comment]
if you checked out the dev version running if very different.

you have to do:
```
pip3 install .
```
then you can just run:
```
msrewards --headless --all
```

**Comment by Ren00d** [comment]
I understand thank you very much the only thing I'm missing I think is a newer version of python ... Since raspberry Pi uses version 3.5.3 ... 
I have installed 3.6.2 but can't figure out how to either uninstall 3.5.3 or tell the pi tu use 3.6.2 by default ... 
Stock  there for now .. haha 
Thanks for your help ...can't wait to try this bot

**Comment by ShoGinn** [comment]
You have to find out where the version is at ;) sometimes its in /usr/bin/python3.6 etc

**Comment by Ren00d** [comment]
I know where version 3.6.2 is  ... Do I just open the CMD from that folder and run msrewards from there ?

**Comment by ShoGinn** [comment]
so as an example:
```
root@debian:~# ls -al /usr/bin/python*
lrwxrwxrwx 1 root root       9 Jan 24  2017 /usr/bin/python -> python2.7
lrwxrwxrwx 1 root root       9 Jan 24  2017 /usr/bin/python2 -> python2.7
-rwxr-xr-x 1 root root 3779512 Sep 26  2018 /usr/bin/python2.7
lrwxrwxrwx 1 root root      33 Sep 26  2018 /usr/bin/python2.7-config -> x86_64-linux-gnu-python2.7-config
lrwxrwxrwx 1 root root      16 Jan 24  2017 /usr/bin/python2-config -> python2.7-config
-rwxr-xr-x 1 root root     154 Sep 21  2016 /usr/bin/python2-pbr
-rwxr-xr-x 1 root root    5694 Sep  8  2016 /usr/bin/python2-wsdump
lrwxrwxrwx 1 root root       9 Jan 20  2017 /usr/bin/python3 -> python3.5
-rwxr-xr-x 2 root root 4751184 Sep 27  2018 /usr/bin/python3.5
lrwxrwxrwx 1 root root      33 Sep 27  2018 /usr/bin/python3.5-config -> x86_64-linux-gnu-python3.5-config
-rwxr-xr-x 2 root root 4751184 Sep 27  2018 /usr/bin/python3.5m
lrwxrwxrwx 1 root root      34 Sep 27  2018 /usr/bin/python3.5m-config -> x86_64-linux-gnu-python3.5m-config
lrwxrwxrwx 1 root root      10 Jan 20  2017 /usr/bin/python3m -> python3.5m
lrwxrwxrwx 1 root root      16 Jan 24  2017 /usr/bin/python-config -> python2.7-config
```

You will see tons of links to python 3.5

If you have a python3.6 in there just run 

```
python3.6 /usr/local/bin/msrewards --headless --all
```

**Comment by Ren00d** [comment]
Import requests
Module not Found error: no module named request 🤔

**Comment by Ren00d** [comment]
So it want to work but get stuck at import requests ..... "No module named requests"
But I do have requests installed. 🤔

**Comment by ShoGinn** [comment]
@Ren00d I can only advise you to do some googling on how to deconflict python versions.
seems to me that the library links are all sorts of screwed up.

my guess is if you look in /usr/local/bin and /usr/local/lib you are going to see some duplication.

And in fact I bet that in /usr/local/lib/python3.6/site-packages there will not be requests or even the msrewards stuff....

I'm going to close this issue as a DIY fix not related to the script itself.

**Comment by Ren00d** [comment]
Ok I got 3.7 on there properly thanks to new debian buster ;) ... 
My issue now is:
OSError: [Errno 8] Exec format error: 'drivers/chromedriver'

Thank you for your help
