### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by z0oinks** [xMNG/Microsoft-Rewards-Bot#29]
Been getting this error for the past couple days:

```DevTools listening on ws://127.0.0.1:49427/devtools/browser/30621e6f-f2be-483a-ad8e-9b4f8b56a3d0

DevTools listening on ws://127.0.0.1:49523/devtools/browser/c777f7d1-c84e-4c38-afd5-130a2dd2d295
Traceback (most recent call last):
  File "ms_rewards.py", line 804, in <module>
    iter_dailies()
  File "ms_rewards.py", line 514, in iter_dailies
    lightning_quiz()
  File "ms_rewards.py", line 583, in lightning_quiz
    find_by_css('.cico.btCloseBack')[0].click()
IndexError: list index out of range```

**Comment by ShoGinn** [comment]
This is the exact error you get because of the new quiz type @xMNG 
#28
