### ISSUE TITLE
SyntaxError: invalid syntax, url, line 93

### ISSUE THREAD

**Issue by Flavien06** [xMNG/Microsoft-Rewards-Bot#4]
I have this error :

>   File "ms_rewards.py", line 93
>     url = f'https://trends.google.com/trends/api/dailytrends?hl=en-US&ed={date}&geo=US&ns=15'
>                                                                                             ^
> SyntaxError: invalid syntax

(Test with Raspbian and Windows 10 ubuntu shell)

**Comment by xMNG** [comment]
Hi there, which python version are you running? F-strings require python version 3.6+. I think Ubuntu comes with python 2 out of the box.

**Comment by Flavien06** [comment]
Ok thank, I have python 3.4.2
Works with 3.6

but ...

> python3.6 ms_rewards.py --headless --mobile --pc --quizTraceback (most recent call last):
>   File "ms_rewards.py", line 696, in <module>
>     browser = browser_setup(parser.headless_setting, MOBILE_USER_AGENT)
>   File "ms_rewards.py", line 134, in browser_setup
>     firefox_browser_obj = webdriver.Firefox(options=options, firefox_profile=profile)
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 157, in __init__
>     self.service.start()
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
>     stdin=PIPE)
>   File "/usr/local/lib/python3.6/subprocess.py", line 707, in __init__
>     restore_signals, start_new_session)
>   File "/usr/local/lib/python3.6/subprocess.py", line 1326, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> OSError: [Errno 8] Exec format error

**Comment by ShoGinn** [comment]
do you have the web driver installed?

**Comment by xMNG** [comment]
Thanks ShoGinn, yeah it looks like a missing geckodriver. Flavien, see the readme for installation information and let us know if you have any further problems.

**Comment by Flavien06** [comment]
Yes, I think I installed it well.
No error in consol but in file ms_rewards.log

> 2018-12-01 12:10:40,181 :: INFO :: root :: ---------------------------------
> 2018-12-01 12:10:40,186 :: INFO :: root :: --------------New----------------
> 2018-12-01 12:10:40,191 :: INFO :: root :: ---------------------------------
> 2018-12-01 12:10:40,247 :: INFO :: root :: args parsed.
> 2018-12-01 12:10:40,255 :: INFO :: root :: logins retrieved.
> 2018-12-01 12:11:01,372 :: INFO :: root :: # of search items: 120
> 
> 2018-12-01 12:11:01,394 :: INFO :: root :: ************MOBILE***************
> 2018-12-01 12:11:02,686 :: ERROR :: root :: Failure at main()
> Traceback (most recent call last):
>   File "ms_rewards.py", line 696, in <module>
>     browser = browser_setup(parser.headless_setting, MOBILE_USER_AGENT)
>   File "ms_rewards.py", line 134, in browser_setup
>     firefox_browser_obj = webdriver.Firefox(options=options, firefox_profile=profile)
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 157, in __init__
>     self.service.start()
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 98, in start
>     self.assert_process_still_running()
>   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
>     % (self.path, return_code)
> selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: -11

**Comment by ShoGinn** [comment]
Not to be a dumb question guy, but you have Firefox installed correct?

**Comment by xMNG** [comment]
interesting catch, I checked my logs and couldn't reproduce this problem. I will make some changes, I have some time this weekend to update the bot.
