### ISSUE TITLE
Bot not maxing out potential points

### ISSUE THREAD

**Issue by Bentechy66** [xMNG/Microsoft-Rewards-Bot#47]
My MS rewards bot logs contain the following error over and over:

`Traceback (most recent call last):
  File "/srv/Microsoft-Rewards-Bot/ms_rewards.py", line 827, in <module>
    log_in(email, password)
  File "/srv/Microsoft-Rewards-Bot/ms_rewards.py", line 205, in log_in
    wait_until_visible(By.ID, 'uhfLogo', 10)
  File "/srv/Microsoft-Rewards-Bot/ms_rewards.py", line 282, in wait_until_visible
    if browser.find_element(by=by_, value=selector):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"uhfLogo"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-135-generic x86_64)`

Note that I am level 2.

**Comment by ShoGinn** [comment]
Noticed you were in England, apparently non-us accounts are having some different issues. I guess we need to find a more generic way to navigate if there are localization issues.

**Comment by MacMarde** [comment]
I have opened some issues about german accounts and also posted a working solution. Maybe it will also gonna help you.
