### ISSUE TITLE
Wrong version of Chrome?

### ISSUE THREAD

**Issue by DaFees** [xMNG/Microsoft-Rewards-Bot#57]
This bot currently refuses to run and I think it has something to do with the version of Chrome I have. When I open Chrome and check it says I have version 76 and that it is up to date. Based on the log below I think my version is too new!

2019-05-06 16:41:32,705 :: INFO :: root :: --------------------------------------------------
2019-05-06 16:41:32,706 :: INFO :: root :: -----------------------New------------------------
2019-05-06 16:41:32,706 :: INFO :: root :: --------------------------------------------------
2019-05-06 16:41:32,706 :: INFO :: root :: logins retrieved.
2019-05-06 16:41:49,673 :: INFO :: root :: # of search items: 244

2019-05-06 16:41:49,673 :: INFO :: root :: -------------------------MOBILE-------------------------
2019-05-06 16:41:53,327 :: ERROR :: root :: Failure at main()
Traceback (most recent call last):
  File "H:\programs\Microsoft-Rewards-Bot-master\ms_rewards.py", line 857, in <module>
    browser = browser_setup(parser.headless_setting, MOBILE_USER_AGENT)
  File "H:\programs\Microsoft-Rewards-Bot-master\ms_rewards.py", line 232, in browser_setup
    chrome_obj = webdriver.Chrome(path, chrome_options=options)
  File "H:\programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "H:\programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "H:\programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "H:\programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "H:\programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

**Comment by ShoGinn** [comment]
Well I guess if you are running the dev version of Chrome that makes sense.

As of right now the stable version of chromedriver is downloaded.

IF you want to modify your version of the code to work.

https://github.com/xMNG/Microsoft-Rewards-Bot/blob/433d07cf347a44c9f9cf189ddb21b561bd413041/ms_rewards.py#L178

Take that line and change `LATEST_RELEASE` to `LATEST_RELEASE_75` and see if that works

**Comment by DaFees** [comment]
I don't know how I ended up with a dev build of Chrome installed. So I uninstalled that and promptly installed the official stable version. Now this is all working fine. Naturally I didn't think my issue was with this program but if it was I wanted you to be aware and if it wasn't I figured you could help me sort it out.
