### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Emeraldop** [xMNG/Microsoft-Rewards-Bot#59]
2019-05-09 17:29:47,876 :: ERROR :: root :: Click by ID to btoption0 element not visible or clickable.
Traceback (most recent call last):
  File "ms_rewards.py", line 425, in click_by_id
    browser.find_element_by_id(obj_id).click()
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: headless chrome=74.0.3729.131)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64

**Comment by ShoGinn** [comment]
Did you run it again and see if it worked?

Is this the normal branch or dev?

**Comment by Emeraldop** [comment]
normal

Sent from Mail for Windows 10

**Comment by Emeraldop** [comment]
should I try dev

**Comment by ShoGinn** [comment]
If you run the script again does it produce the same error?

It is trying to complete a daily poll.. I have not seen any changes on daily polls, the dev version has the same code for polls.

**Comment by Emeraldop** [comment]
Yes

**Comment by ShoGinn** [comment]
Did this correct itself? Or is it fixed?

**Comment by Emeraldop** [comment]
Yes I think so I started using the dev version also I just received this in my log on the dev version is this an error? "2019-05-12 13:51:04 : INFO :: myemail@gmail.com :: ms_rewards : WebDriverException while executing
Traceback (most recent call last):
  File "C:\Users\emerald\Documents\Rewardz\Microsoft-Rewards-Bot-dev\rewardsbot\ms_rewards.py", line 689, in run_it
    search_progress = self.get_search_progress()
  File "C:\Users\emerald\Documents\Rewardz\Microsoft-Rewards-Bot-dev\rewardsbot\ms_rewards.py", line 281, in get_search_progress
    web_elements = self.driver.find_element_by_class_name('pcsearch')
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 563, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\emerald\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"pcsearch"}
  (Session info: headless chrome=74.0.3729.131)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)"

**Comment by ShoGinn** [comment]
These are all errors that are very odd :)

Has the script ever worked?

**Comment by jbfreels** [comment]
I was getting the same error on my linux desktop as well as my pi early this morning.  Both are now resolved.  I think the website was having issues.
