### ISSUE TITLE
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 33 (char 32)

### ISSUE THREAD

**Issue by Samasaur1** [xMNG/Microsoft-Rewards-Bot#6]
When running it after a fresh install of Selenium and Geckodriver using a Homebrew install, this error occurs.
```
Traceback (most recent call last):
  File "ms_rewards.py", line 697, in <module>
    login_dict = get_login_info()
  File "ms_rewards.py", line 129, in get_login_info
    return json.load(f)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 33 (char 32)
```

I've got no Python knowledge, so any help would be greatly appreciated. Thanks!

**Comment by xMNG** [comment]
It may also be that you have an out of place new line on character 32:
```json.decoder.JSONDecodeError: Invalid \escape: line 1 column 33 (char 32)```

**Comment by Samasaur1** [comment]
Thanks guys! I'm not sure why I didn't read the title *of my own issue*, but sure enough I looked at the file and my password had a `\` in it — which would definitely count as an `invalid \escape`.

I changed my password, so I'm good, but perhaps so that others don't encounter this problem, you should tell them to escape backslashes somewhere on your README

Thanks again!
