### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by lukedukeus** [xMNG/Microsoft-Rewards-Bot#8]
cmd shows this, 

C:\Users\vanzw\OneDrive\Desktop\Microsoft-Rewards-Bot-master>python3 ms_rewards.py --headless --mobile --pc --quiz
Traceback (most recent call last):
  File "ms_rewards.py", line 726, in <module>
    search(search_list, mobile_search=True)
  File "ms_rewards.py", line 407, in search
    if get_point_total(mobile=True):
  File "ms_rewards.py", line 616, in get_point_total
    current_point_total = list(map(int, browser.find_element_by_class_name('credits2').text.split(' of ')))[0]
ValueError: invalid literal for int() with base 10: ''
 

and the error log shows this:

2019-01-21 15:23:40,392 :: INFO :: root :: ***************MOBILE***************
2019-01-21 15:23:47,871 :: INFO :: root :: Logging in ++++++++@outlook.com...
2019-01-21 15:24:02,440 :: INFO :: root :: Search Start
2019-01-21 15:24:23,093 :: ERROR :: root :: credits2 element Not Visible - Timeout Exception
2019-01-21 15:24:23,093 :: ERROR :: root :: credits2 cannot be located.
Traceback (most recent call last):
  File "ms_rewards.py", line 219, in wait_until_visible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\Users\vanzw\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

what am i doing wrong?

**Comment by ShoGinn** [comment]
This is a known error. 
The developer needs to update the locator. Look at the other issue about it. 
If you are saavy you can modify the code ;)

**Comment by lukedukeus** [comment]
what is the locator?

**Comment by ShoGinn** [comment]
this is the same as #7
