### ISSUE TITLE
Error won't start

### ISSUE THREAD

**Issue by tomjfmu3** [xMNG/Microsoft-Rewards-Bot#83]
2019-06-18 15:22:51,585 :: INFO :: root :: --------------------------------------------------
2019-06-18 15:22:51,585 :: INFO :: root :: -----------------------New------------------------
2019-06-18 15:22:51,586 :: INFO :: root :: --------------------------------------------------
2019-06-18 15:22:51,586 :: INFO :: root :: logins retrieved.
2019-06-18 15:23:05,396 :: INFO :: root :: # of search items: 140

2019-06-18 15:23:05,396 :: INFO :: root :: -------------------------MOBILE-------------------------
2019-06-18 15:23:09,025 :: ERROR :: root :: Failure at main()
Traceback (most recent call last):
  File "ms_rewards.py", line 869, in <module>
    browser = browser_setup(parser.headless_setting, MOBILE_USER_AGENT)
  File "ms_rewards.py", line 243, in browser_setup
    chrome_obj = webdriver.Chrome(path, chrome_options=options)
  File "C:\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 75

**Comment by tomjfmu3** [comment]
I figured out I had to downgrade chrome
