### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by wolfaustin47** [xMNG/Microsoft-Rewards-Bot#93]
Hey! 
So this is the issue i get when i try to run the bot. I've made sure that the login info in the login dict was JSON appropriate. I am not entirely sure what is going wrong, please help.

Traceback (most recent call last):
  File "ms_rewards.py", line 865, in <module>
    search_list = get_search_terms()
  File "ms_rewards.py", line 170, in get_search_terms
    response = json.loads(request.text[5:])
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by niallwatchorn** [comment]
Am also seeing this issue. I have python 3.6 installed and successfully installed the requirements file.

**Comment by niallwatchorn** [comment]
Hi @wolfaustin47, did you find a fix for this?

**Comment by wolfaustin47** [comment]
Yeah, I had to completely reinstall my OS :/. Something along the way must have been broken but a fresh install worked. Good luck 👍
