### ISSUE TITLE
Bot crashes with --quiz option

### ISSUE THREAD

**Issue by Bluethefurry** [xMNG/Microsoft-Rewards-Bot#95]
Not sure what causes this, but trying to have the bot complete quizzes only prompts this error:

```
2019-07-29 09:24:59,486 :: ERROR :: root :: WebDriverException while executing pc portion
Traceback (most recent call last):
  File "/root/msrewards/ms_rewards.py", line 923, in <module>
    iter_dailies()
  File "/root/msrewards/ms_rewards.py", line 603, in iter_dailies
    sign_in_prompt()
  File "/root/msrewards/ms_rewards.py", line 759, in sign_in_prompt
    browser.find_element_by_link_text('Sign in').click()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 427, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Sign in"}
  (Session info: headless chrome=75.0.3770.142)
  (Driver info: chromedriver=75.0.3770.140 (2d9f97485c7b07dc18a74666574f19176731995c-refs/branch-heads/3770@{#1155}),platform=Linux 4.19.0-5-amd64 x86_64)
```

it also doesnt seem to recognise finished searches for me, so it may be related to #48

**Comment by Bluethefurry** [comment]
it just now started working again but didnt for the past 2 days, this is weirdddd
